CODE SEGMENT   
    ASSUME CS:CODE
    MOV CL, 0 ; INIT
NEXT: 
    CALL PUTNUM ; CALL SUBROUTINE
    INC CL ; CL ++
    CMP CL, 10 ; IF CL < 10
    JB NEXT ; GO TO NEXT

    MOV AH, 4CH
    INT 21H
PUTNUM:
    MOV DL, CL
    ADD DL, '0' ; INT2STR
    MOV AH, 2
    INT 21H
    RET
CODE ENDS
END